/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  safelist: [
    // Preserve dynamically-built puzzle group classes (e.g. bg-group-${color}-base).
    {
      pattern: /^bg-group-(red|blue|green|yellow|purple|pink|teal|indigo|amber)-base$/,
    },
  ],
  theme: {
    extend: {
      colors: {
        app: {
          bg: '#0f172a',
          bgAlt: '#020617',
          surface: '#1e293b',
          surfaceMuted: '#0f172a',
          border: '#334155',
          borderStrong: '#475569',
          text: '#f8fafc',
          textMuted: '#cbd5e1',
        },
        group: {
          // Queens/shared puzzle palette tokens
          red: {
            base: '#991B1B',
            hover: '#B91C1C',
          },
          blue: {
            base: '#2563EB',
            hover: '#3B82F6',
          },
          green: {
            base: '#166534',
            hover: '#15803D',
          },
          yellow: {
            base: '#FDE047',
            hover: '#FACC15',
          },
          purple: {
            base: '#7E22CE',
            hover: '#9333EA',
          },
          pink: {
            base: '#EC4899',
            hover: '#F472B6',
          },
          teal: {
            base: '#0891B2',
            hover: '#06B6D4',
          },
          indigo: {
            base: '#312E81',
            hover: '#4338CA',
          },
          amber: {
            base: '#92400E',
            hover: '#B45309',
          },
        },
        queens: {
          gradientStart: '#1a2740',
          gradientEnd: '#0d1117',
          gridLine: '#94a3b8',
        },
        incremental: {
          shellBg: '#020617',
          shellText: '#f1f5f9',
          title: '#67e8f9',
          mutedText: '#cbd5e1',
          panelBg: '#0f172a',
          panelBgElevated: '#1e293b',
          panelBgStrong: '#111827',
          border: '#334155',
          borderSoft: '#475569',
          borderMuted: '#64748b',
          timerUrgent: '#fca5a5',
          timerWarning: '#fde68a',
          warningText: '#fde68a',
          scoreText: '#fde68a',
          bankText: '#6ee7b7',
          badgeInfoBorder: '#0ea5e9',
          badgeInfoText: '#7dd3fc',
          successBorder: '#34d399',
          successBg: '#10b981',
          successText: '#6ee7b7',
          successTextSoft: '#a7f3d0',
          dangerBorder: '#991b1b',
          dangerBorderHover: '#b91c1c',
          dangerBg: '#7f1d1d',
          dangerBgHover: '#991b1b',
          dangerText: '#fee2e2',
          warningBorder: '#b45309',
          warningBorderHover: '#d97706',
          warningBg: '#92400e',
          warningBgHover: '#b45309',
          warningBtnText: '#fef3c7',
          infoBorder: '#1e40af',
          infoBorderHover: '#1d4ed8',
          infoBg: '#1d4ed8',
          infoBgHover: '#2563eb',
          infoText: '#dbeafe',
          accentBorder: '#0f766e',
          accentBg: '#0f766e',
          accentBgHover: '#0d9488',
          accentText: '#ecfeff',
          riskBorder: '#fb7185',
          riskBg: '#881337',
          riskText: '#fff1f2',
          riskTextSoft: '#ffe4e6',
          disabledBg: '#1e293b',
          disabledBgHover: '#334155',
          disabledText: '#cbd5e1',
          disabledTextMuted: '#94a3b8',
        },
        plaque: {
          ink: '#131313',
          forest: '#0f3b2e',
          forestDeep: '#144b1a',
          forestBright: '#2d8b3a',
          maroon: '#4a1111',
          gold: '#d4af37',
          goldLight: '#e6c766',
          parchment: '#f2f1ea',
        },
        nature: {
          moss: '#3a4a1b',
          leafDark: '#144b1a',
          leafMid: '#1a5a22',
          leafBright: '#2d8b3a',
          leafBrightest: '#3a9b4a',
          actionBlue: '#2563eb',
          actionMuted: '#64748b',
        },
        status: {
          danger: '#ef4444',
          warning: '#f59e0b',
          success: '#10b981',
        },
      },
    },
  },
  plugins: [],
};
