package com.queens.admin.domain.model

enum class ActionType {
    CREATE_BOARD,
    CLEAR_BOARD,
    VALIDATE_BOARD,
    SET_CELL_COLOR,
    CLEAR_CELL_COLOR,
    PLACE_FLAG,
    REMOVE_FLAG,
    PLACE_QUEEN,
    REMOVE_QUEEN,
    PLACE_QUEENS,
    ASSIGN_INITIAL_COLORS,
    EXPAND_ALL_GROUPS_ONCE,
    EXPAND_SELECTED_GROUP,
    EXPAND_BLOCKED_SQUARES,
    GENERATE_VALID_BOARD,
    CLEAR_SOLVER_MARKS,
    RUN_NEXT_SOLVER_STEP,
    RUN_SPECIFIC_SOLVER_RULE,
    RUN_ALL_SOLVER_STEPS,
    COMPUTE_CANONICAL_SIGNATURE,
}
