server:
  port: 8080

spring:
  application:
    name: queens-admin-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/queens_admin}
    username: ${SPRING_DATASOURCE_USERNAME:queens_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:queens_admin}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
